import "./globals.css";
import localFont from "next/font/local";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const myFont = localFont({
  src: [
    {
      path: "../assets/fonts/Lato-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Lato-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mainLayout">
        <main className={myFont.className}>{children}</main>
      </body>
    </html>
  );
}
